# Jekyll site settings
# variables accessed via {{ site.title }}, {{ site.email }}, and so on.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Philip-Nicolas
email: philnic.varga@mail.utoronto.ca
description: ""
baseurl: "" 
url: "https://philip-nicolas.github.io"
github_username: Philip-Nicolas

# Build settings
markdown: kramdown
remote-theme: daviddarnes/alembic
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
